### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Manix888** [vizality-community/better-code-blocks#2]
Sorry that I am writing to you in Issues. I I wrote to you by mail but you did not answer.
Question: How can I install your plugins?

**Comment by sepruko** [comment]
> Sorry that I am writing to you in Issues. I I wrote to you by mail but you did not answer.
> Question: How can I install your plugins?

What client mod do you use?

**Comment by Manix888** [comment]
> > Sorry that I am writing to you in Issues. I I wrote to you by mail but you did not answer.
> > Question: How can I install your plugins?
> 
> What client mod do you use?

Hi! I am using BetterDiscord

**Comment by sepruko** [comment]
> > > Sorry that I am writing to you in Issues. I I wrote to you by mail but you did not answer.
> > > Question: How can I install your plugins?
> > 
> > 
> > What client mod do you use?
> 
> Hi! I am using BetterDiscord

This plugin does not support BetterDiscord unfortunately, there are no compatibility plugins for BetterDiscord that will allow this plugin to work, either.

**Comment by resucutie** [comment]
Also note: this plugin is only available for Vizality (which wasn't relased for public usage btw), so you need to wait until relase.

By the way, don't forget to close this issue if you don't have more questions

**Comment by dperolio** [comment]
Hey Manix, sorry, I didn't receive your email, but as others have said this plugin is meant to be used with the Vizality client mod which is currently undergoing closed alpha testing, which just began last week. To find out more info and to possibly become eligible to beta test when the option becomes available, I recommend you join our Discord server at https://invite.vizality.com.

Thanks.
